### ISSUE TITLE
Version 3.5.0 broke application

### ISSUE THREAD

**Issue by YuriFontella** [fastify/fastify-autoload#139]
I upgraded from version 3.4.2 to 3.5.0 and influenced the operation of other plugins.

![image](https://user-images.githubusercontent.com/4920619/108910229-556bb180-7604-11eb-9543-e46b4096c85a.png)

This is my structure:
[https://github.com/YuriFontella/fastify-api](https://github.com/YuriFontella/fastify-api)

**Comment by Eomm** [comment]
It seems related to
https://github.com/fastify/fastify-autoload/pull/136

Could you update to 3.5.1?

**Comment by roelvan** [comment]
I got this issue after updating to 3.5.0 (no version found at 3.5.1):

```
TypeError: Cannot read property 'bind' of undefined
    at /home/roel/Repos/kwis-api-fastify/node_modules/fastify/lib/route.js:272:31
    at Array.map (<anonymous>)
    at Boot.<anonymous> (/home/roel/Repos/kwis-api-fastify/node_modules/fastify/lib/route.js:271:14)
    at Object.onceWrapper (events.js:421:28)
    at Boot.emit (events.js:327:22)
    at Boot.EventEmitter.emit (domain.js:467:12)
    at /home/roel/Repos/kwis-api-fastify/node_modules/avvio/boot.js:153:12
    at /home/roel/Repos/kwis-api-fastify/node_modules/avvio/plugin.js:269:7
    at done (/home/roel/Repos/kwis-api-fastify/node_modules/avvio/plugin.js:201:5)
    at check (/home/roel/Repos/kwis-api-fastify/node_modules/avvio/plugin.js:225:9)
    at internal/process/task_queues.js:149:7
    at AsyncResource.runInAsyncScope (async_hooks.js:197:9)
    at AsyncResource.runMicrotask (internal/process/task_queues.js:146:8)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by YuriFontella** [comment]
"No matching version found for fastify-autoload@3.5.1" using npm

**Comment by mcollina** [comment]
weird, it's out now.

**Comment by mcollina** [comment]
FYI, the example does not run:

```
(node:2090) UnhandledPromiseRejectionWarning: Error: Cannot find module '../../knexfile'
Require stack:
- /home/matteo/repositories/autoload-bug/src/plugins/knex.js
- /home/matteo/repositories/autoload-bug/node_modules/fastify-autoload/index.js
- /home/matteo/repositories/autoload-bug/app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/matteo/repositories/autoload-bug/src/plugins/knex.js:5:12)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2090) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:2090) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by mcollina** [comment]
Anyway, I've tested with v3.5.2 and it fixes the problem.
